language: cpp
sudo: required

os:
  - linux
  - osx

branches:
  except:
  - gh_pages
  - DebianPackaging

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install -y libwxgtk3.0-dev libwxgtk3.0 gettext doxygen graphviz rpm; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-verbose -c https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.tar.gz ; tar xzf cmake-3.10.1-Linux-x86_64.tar.gz ; export PATH=$(pwd)/cmake-3.10.1-Linux-x86_64/bin:$PATH ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH";brew install ccache; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/texinfo/bin:$PATH:/usr/local/opt/gettext/bin ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxwidgets gettext texinfo ; fi

notification:
  email:
    recipients:
      - andrej.vodopivec@gmail.com
    on_success: change
    on_failure: change

git:
  depth: 15

script:
 - mkdir build && cd build
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="-Wall -Wextra -fcolor-diagnostics"; else export CXXFLAGS="-Wall -Wextra"; fi
 - cmake ..
 - cmake --build .
 # OSX builds are slow even without building the documentation and doxygen should
 # do the same on all operatings systems, anyway as it is based on wxWidgets ;-)
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake --build . -- html ; fi
 - cmake --build . -- install DESTDIR=$(pwd)/installtest
 - cmake --build . -- package
