language: cpp
sudo: required

os:
  - linux
  - osx

osx_image: xcode8.3

branches:
  except:
  - gh_pages
  - DebianPackaging

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0 gettext doxygen graphviz rpm ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -c https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz ; tar xzf cmake-3.9.0-Linux-x86_64.tar.gz ; export PATH=$(pwd)/cmake-3.9.0-Linux-x86_64/bin:$PATH ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxwidgets gettext texinfo doxygen graphviz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/texinfo/bin:$PATH:/usr/local/opt/gettext/bin ; fi

notification:
  email:
    recipients:
      - andrej.vodopivec@gmail.com
    on_success: change
    on_failure: change

git:
  depth: 15

script: mkdir build && cd build && CXXFLAGS=-Wall cmake .. && cmake --build . && cmake --build . -- html && cmake --build . -- install DESTDIR=$(pwd)/installtest && cmake --build . package
